# Generated by Django 5.2.8 on 2026-01-28 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userrole_remove_user_hourly_rate_remove_user_role_and_more'),
    ]

    operations = [
    ]
