# Generated by Django 5.2.8 on 2026-01-28 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_seed_user_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContabilitaCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_at', models.DateTimeField(auto_now=True)),
                ('checked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contabilita_checks', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checked_by_contabilita', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('checked_by', 'user')},
            },
        ),
    ]
