# Generated by Django 5.2.8 on 2025-11-08 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='role',
            field=models.CharField(choices=[('bagnino', 'Bagnino'), ('istruttore', 'Istruttore'), ('segreteria', 'Segreteria'), ('pulizia', 'Pulizia')], max_length=20),
        ),
        migrations.CreateModel(
            name='PayRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('bagnino', 'Bagnino'), ('istruttore', 'Istruttore'), ('segreteria', 'Segreteria'), ('pulizia', 'Pulizia')], max_length=20)),
                ('pay_type', models.CharField(choices=[('hour', 'Per ora'), ('shift', 'Per turno')], default='hour', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'role')},
            },
        ),
    ]
