# Generated by Django 5.2.8 on 2025-11-08 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('shifts', '0003_templateshift'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templateshift',
            name='role',
        ),
        migrations.AddField(
            model_name='templateshift',
            name='category',
            field=models.CharField(choices=[('bagnini', 'Bagnini'), ('istruttori', 'Istruttori'), ('segreteria', 'Segreteria'), ('pulizie', 'Pulizie')], default='bagnini', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='templateshift',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.course'),
        ),
        migrations.AlterField(
            model_name='templateshift',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
