# Generated by Django 5.2.8 on 2025-11-16 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0004_remove_templateshift_role_templateshift_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplacementRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partial', models.BooleanField(default=False)),
                ('partial_start', models.TimeField(blank=True, null=True)),
                ('partial_end', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'In attesa'), ('accepted', 'Accettata'), ('rejected', 'Rifiutata'), ('cancelled', 'Cancellata')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replacement_requests_made', to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replacement_requests', to='shifts.shift')),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replacement_requests_received', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
