# Generated by Django 5.2.8 on 2025-11-24 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0005_replacementrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templateshift',
            name='category',
            field=models.CharField(choices=[('bagnino', 'Bagnino'), ('istruttore', 'Istruttore'), ('segreteria', 'Segreteria'), ('pulizia', 'Pulizia')], max_length=20),
        ),
        migrations.CreateModel(
            name='PublishedWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('category', 'start_date')},
            },
        ),
    ]
