# Generated by Django 5.2.8 on 2025-11-25 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0006_alter_templateshift_category_publishedweek'),
    ]

    operations = [
        migrations.AddField(
            model_name='replacementrequest',
            name='original_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='replacementrequest',
            name='original_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
