# Generated by Django 5.2.8 on 2025-11-25 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0007_replacementrequest_original_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='original_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='original_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
