# Generated by Django 5.2.8 on 2025-11-25 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0008_shift_original_end_time_shift_original_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='original_end_time',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='original_start_time',
        ),
    ]
