# Generated by Django 5.2.8 on 2025-11-27 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_categorybaserate_coursetype_userhourlyrate_and_more'),
        ('shifts', '0010_replacementrequest_closed_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='course',
        ),
        migrations.RemoveField(
            model_name='templateshift',
            name='course',
        ),
        migrations.AddField(
            model_name='shift',
            name='course_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.coursetype'),
        ),
        migrations.AddField(
            model_name='templateshift',
            name='course_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.coursetype'),
        ),
    ]
