# Generated by Django 5.2.8 on 2026-01-16 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0011_remove_shift_course_remove_templateshift_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='replacementrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
