# Generated by Django 5.2.8 on 2026-02-05 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0012_replacementrequest_updated_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PayRate',
        ),
    ]
