# Generated by Django 5.2.8 on 2025-11-27 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_categorybaserate_coursetype_userhourlyrate_and_more'),
        ('shifts', '0011_remove_shift_course_remove_templateshift_course_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
