# Generated by Django 5.2.8 on 2026-02-06 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_refactor_categorybaserate_to_use_userrole'),
        ('users', '0005_populate_user_roles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorybaserate',
            options={'verbose_name': 'Tariffa base per categoria', 'verbose_name_plural': 'Tariffe base per categoria'},
        ),
        migrations.AlterField(
            model_name='categorybaserate',
            name='base_rate',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Tariffa base (€/h)'),
        ),
        migrations.AlterField(
            model_name='categorybaserate',
            name='role',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='base_rate', to='users.userrole', verbose_name='Ruolo'),
        ),
    ]
